[project]
name = "torchquantum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
"matplotlib>=3.3.2",
"numpy>=1.19.2",

"opt_einsum",
"pathos>=0.2.7",
"pylatexenc>=2.10",
"qiskit>=2.0.0",
"recommonmark",
"qiskit_ibm_runtime",
"qiskit-aer>=0.17.0",

"scipy>=1.5.2",
"setuptools>=52.0.0",
"torch",
"torchdiffeq>=0.2.3",
"torchpack>=0.3.0",
"torchvision",
"tqdm>=4.56.0"

]
